require 'monkey/hp'
require 'monkey/hp/block_storage'
require 'monkey/hp/cdn'
require 'monkey/hp/compute'
require 'monkey/hp/dns'
require 'monkey/hp/storage'
require 'monkey/hp/requests/storage/post_object'
